//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionWEBMuseum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTISTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ARTISTA()
        {
            this.CONTENIDO = new HashSet<CONTENIDO>();
        }
    
        public int id_artista { get; set; }
        public string nombres_artista { get; set; }
        public string apellidos_artista { get; set; }
        public string genero_artista { get; set; }
        public System.DateTime fechanacimiento_artista { get; set; }
        public string descripcion_artista { get; set; }
        public System.DateTime fechacreacion_artista { get; set; }
        public string estado_artista { get; set; }
        public string nacionalidad_artista { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTENIDO> CONTENIDO { get; set; }
    }
}
