//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionWEBMuseum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTENIDO()
        {
            this.EXPOSICION = new HashSet<EXPOSICION>();
            this.EXPOSICION_CONTENIDO = new HashSet<EXPOSICION_CONTENIDO>();
        }
    
        public int id_contenido { get; set; }
        public byte[] imagen_contenido { get; set; }
        public string titulo_contenido { get; set; }
        public string descripcion_contenido { get; set; }
        public Nullable<System.DateTime> fechacreacion_contenido { get; set; }
        public Nullable<int> artista_contenido { get; set; }
        public string estado_contenido { get; set; }
        public Nullable<int> visitas_contenido { get; set; }
    
        public virtual ARTISTA ARTISTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPOSICION> EXPOSICION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPOSICION_CONTENIDO> EXPOSICION_CONTENIDO { get; set; }
    }
}
