//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionWEBMuseum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENTO()
        {
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public int id_evento { get; set; }
        public string titulo_evento { get; set; }
        public string descripcion_evento { get; set; }
        public System.DateTime fechacreacion_evento { get; set; }
        public string estado_evento { get; set; }
        public Nullable<System.DateTime> fechainicio_evento { get; set; }
        public Nullable<System.DateTime> fechatermino_evento { get; set; }
        public Nullable<int> participantes_evento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
