//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionWEBMuseum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPOSICION_CONTENIDO
    {
        public int id_exposicion_contenido { get; set; }
        public int exposicion { get; set; }
        public int contenido { get; set; }
        public System.DateTime fechacreacion { get; set; }
    
        public virtual CONTENIDO CONTENIDO1 { get; set; }
        public virtual EXPOSICION EXPOSICION1 { get; set; }
    }
}
