//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionWEBMuseum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPOSICION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXPOSICION()
        {
            this.EXPOSICION_CONTENIDO = new HashSet<EXPOSICION_CONTENIDO>();
        }
    
        public int id_exposicion { get; set; }
        public int referencia_exposicion { get; set; }
        public string titulo_exposicion { get; set; }
        public string descripcion_exposicion { get; set; }
        public System.DateTime fechacreacion_exposicion { get; set; }
        public string estado_exposicion { get; set; }
        public Nullable<int> visitas { get; set; }
        public System.DateTime fechainicio_exposicion { get; set; }
        public System.DateTime fechatermino_exposicion { get; set; }
    
        public virtual CONTENIDO CONTENIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPOSICION_CONTENIDO> EXPOSICION_CONTENIDO { get; set; }
    }
}
