//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolucionWEBMuseum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public string id_solicitud { get; set; }
        public string nombre_solicitante { get; set; }
        public string apellido_solicitante { get; set; }
        public string descripcion_solicitud { get; set; }
        public int evento_solicitud { get; set; }
        public string correo_solicitud { get; set; }
        public int celular_solicitud { get; set; }
        public string estado { get; set; }
        public string estadopendiente_solicitud { get; set; }
        public Nullable<System.DateTime> fecharespuesta_solicitud { get; set; }
        public System.DateTime fechacreacion_solicitud { get; set; }
    
        public virtual EVENTO EVENTO { get; set; }
    }
}
